### ISSUE TITLE
FrontendPluginRegistry - modify source on the fly

### ISSUE THREAD

**Issue by rNoz** [sinelaw/elfs-clang-plugins#2]
Hi,

I have read your blog and your plugins, and It seems you don't use it. I cannot achieve what I want and maybe you know how to do it.

I am able to create a plugin `FrontendPluginRegistry::Add` that uses `ASTConsumer` and `Visitor` pattern, and modify the source code with `Rewriter`. The problem is that I cannot modify the source code that is compiled in that phase. I don't know how to affect the compilation itself. I tried with `AddBeforeMainAction` with no luck.

I only saw an option to overwrite source files, but it will modify the user files and it will need another run to compile the modifications. I just want to modify the files at runtime, in one step. I suppose it will need some sort of "after my plugin is executed, reparse again and run the whole compilation phase again".

I am executing the plugin like this `clang++ ${FLAGS} -Xclang -load -Xclang ${path_to_so} -Xclang -add-plugin -Xclang $plugin_name -o $BIN ${FILE}`.

The thing is that I need a plugin. I don't want to create an independent tool to do it (like `libTooling` with a `main` function).

Regards,
rNoz

**Comment by sinelaw** [comment]
Hi, I'm indeed not using a rewriter. The plugins in this project only emit extra warnings (or errors) and don't affect the compilation itself.
Unfortunately, also I didn't find a way to do what you want - to rewrite the code and compile it in the same run - but that doesn't mean it isn't possible. I didn't really try very hard.

**Comment by rNoz** [comment]
Thanks. If you know the way to go, please, give me some suggestions and I will try ;)
